[[PROPOSAL]]
arch = "aarch64"
git-tree-sha1 = "4f1c2e3d5a963de2d0f3d655c14935e5f3295960"
os = "macos"

    [[PROPOSAL.download]]
    sha256 = "c77a9e50c2a8f500397d692593490787318b8499ec098e3c090277bd228a7080"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.aarch64-apple-darwin.tar.gz"
[[PROPOSAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c842691d5bb74747ae9cc7bdb5d0d9232976a79d"
libc = "glibc"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "c87c84fe79d23c912475cc347242ffc17ad8f113184dad46194cad1e71c1bf74"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[PROPOSAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "512c9333476e343162f59841dd877899a32acc3a"
libc = "musl"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "d16ba0a27ac8ec91ca47def7c87ab34d0cb9b786260293b1d2c2451cc0cae44e"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[PROPOSAL]]
arch = "aarch64"
git-tree-sha1 = "aa5b2f97fc0dd4898071c6298a16d229a88fdfbe"
os = "freebsd"

    [[PROPOSAL.download]]
    sha256 = "85926170af44f93b83022767cebd46310dc843934bf75a3ee8b6110ead3283a2"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.aarch64-unknown-freebsd.tar.gz"
[[PROPOSAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eedb3eef74f236df937ec2ad468e662204786c2"
libc = "glibc"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "10b464af970805c38afcb40809b62225aa71dc31a6133144b18d3c934c79eb68"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.i686-linux-gnu-cxx11.tar.gz"
[[PROPOSAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d6b00264194d6e512dc2cd89a5835900a1f2745"
libc = "musl"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "8c387c4cb6a9f159caed6a9a3e6a46f03e4e5d4ca9b61e2438ed20ecf65fd436"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.i686-linux-musl-cxx11.tar.gz"
[[PROPOSAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faf42fdf560c53782e3b9df2b69c1ea30b711dd0"
libc = "glibc"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "6cedf56967f244b33f1ce61528aac62d41a4cd2a7ec41208ea956e563cb8b90c"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROPOSAL]]
arch = "x86_64"
git-tree-sha1 = "565cf1f309119c4fe1a55797cb3ab396bf3a4111"
os = "macos"

    [[PROPOSAL.download]]
    sha256 = "edea2fd207cf2530bdb62dbd93444ac228bfdc1064515a7c180159c6393d26a0"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.x86_64-apple-darwin.tar.gz"
[[PROPOSAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d95e38716e19c092c040d90beb62a722e6a83740"
libc = "glibc"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "25aedd4a9acfa9be1f9eba9988cb95829409cb47d0af60c84e43bbaf28051980"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[PROPOSAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce5f0a82a242cd75c0303f45029034f9337769e5"
libc = "musl"
os = "linux"

    [[PROPOSAL.download]]
    sha256 = "a9c93d4ed3fe0ce3d8254274ffe10d3caad50d719616e264b1949374f2b3b5bd"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[PROPOSAL]]
arch = "x86_64"
git-tree-sha1 = "9ea251d2a6b2f2ebaef030fcf80ae3971a4322b3"
os = "freebsd"

    [[PROPOSAL.download]]
    sha256 = "d7e4f66a9444b2ad33197aa33ef3c8c884f86ccc8da91fb3289e902bc8949738"
    url = "https://github.com/JuliaBinaryWrappers/PROPOSAL_jll.jl/releases/download/PROPOSAL-v7.6.2+1/PROPOSAL.v7.6.2.x86_64-unknown-freebsd.tar.gz"
