name = "PROPOSAL_jll"
uuid = "a7736f47-6014-525c-ac95-fe8419cd7fa6"
version = "7.6.2+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
spdlog_jll = "3d47416f-b330-5763-8b13-e9bf7bc8d726"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
CubicInterpolation_jll = "b06d284d-2c5b-591e-b85a-2706a7b137dc"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
CubicInterpolation_jll = "0.1.5"
Artifacts = "< 0.0.1, 1"
boost_jll = "=1.79.0"
